### ISSUE TITLE
community plugin

### ISSUE THREAD

**Issue by jwierzbo** [LostPaul/obsidian-folder-notes#1]
Hello!
Are you planing to add it to the community plugins in Obsidian to make install and update process easier?

**Comment by LostPaul** [comment]
> Hello!
> Are you planing to add it to the community plugins in Obsidian to make install and update process easier? 

I applied yesterday you'll have to wait some days until it gets reviewed and I fix changes they request if they do.

**Comment by jwierzbo** [comment]
could you linked that request here?

**Comment by LostPaul** [comment]
https://github.com/obsidianmd/obsidian-releases/pull/1800

**Comment by nhan000** [comment]
Hi @LostPaul, I saw you reference https://github.com/aidenlx/alx-folder-note so I wanted to ask what's the difference between yours and ALX's folder note plugin? 

Sorry for bothering you but I think it'd be helpful for people to see the similarity and difference between plugins. ALX is still active in the community but hasn't worked on his Folder Note plugin for a while and there was a few significant bugs. Thanks a lot!

**Comment by LostPaul** [comment]
> Hi @LostPaul, I saw you reference https://github.com/aidenlx/alx-folder-note so you probably know well what that plugin does. May I ask what's the difference between yours and ALX's folder note plugin?
> 
> Sorry for bothering you but I think it'd be helpful for people to see the similarity and difference between plugins. ALX is still active in the community but hasn't worked on his Folder Note plugin for a while and there was a few significant bugs. Thanks a lot!

Well first of all you currently can't even enable it without having a second plugin downloaded.
I just tried the plugin again and as you mentioned it has some bugs when I tried to create a folder note and click on it didn't work only after I restarted the vault.

For this reason and the fact that they haven't worked on it for more than a year I've decided to create my own plugin.

But the difference between mine plugin and their are only some features that are: Automatically creating folder notes for newly created folders, creating a folder note for every existing folder (well this doesn't work yet because I had some bug with the templater plugin, directly using templates from the templater plugin or the core templates plugin, excluding only really relevant because of the auto create of folder note and just the option to disable the underline for the name of folders that have a folder note.

I didn't create a pr for that on their github repo because it took me some hours and I wasn't even sure if they will merge it or even see it the last few times I did that it didn't get merged most of them mostly because the owners weren't active anymore or had no time to even review it.

**Comment by LostPaul** [comment]
oh I forgot to mention that I also changed the way the folders with folder notes collapse, they only collapse if click on the icon next to the name and clicking on the whitespace around the a folder name doesn't collapse the folder that can be toggle in the settings though and overwritten for specific folders with the exclude folders feature

**Comment by sigrunixia** [comment]
Welcome to the community store :)

**Comment by LostPaul** [comment]
> Welcome to the community plugins list* :)

Thanks
